version: '3.8'

services:
  main-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: maindb
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  covered-bridge:
    build:
      context: ./server
      dockerfile: src/main/docker/dev-jvm.dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - main-db

  example-php:
    build:
      context: ./examples/php
      dockerfile: Dockerfile
    ports:
      - "8001:80"
    depends_on:
      - server

volumes:
  db_data: